name = "Placar"
uuid = "d992d0fe-46de-49a1-9a96-bb7730888bdc"
authors = ["Gustavo Henrique T Cardoso <ghtcardoso@icloud.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
